### ISSUE TITLE
Observability assignment

### ISSUE THREAD

**Issue by gao-ti** [trilogy-group/tu2k22-zhiyuangao#8]
- [x] Milestone 1: OpenTelemetry Tracing
- [x] Milestone 2: OpenTelemetry to Jaeger
- [x] Milestone 3: Prom for django

**Comment by gao-ti** [comment]
## Milestone 1

First, the traces are emitted to the terminal.

Related commit: https://github.com/trilogy-group/tu2k22-zhiyuangao/commit/a55a9a2bc05be81bcb1046f78c63c4810939af24

![image](https://user-images.githubusercontent.com/110180090/184339071-ce56480c-8d9d-4dc3-8754-7d5548158a4e.png)

**Comment by gao-ti** [comment]
## Milestone 3 Prom
View results at http://localhost:9090/graph?g0.range_input=1h&g0.stacked=1&g0.expr=django_http_requests_total_by_method_total&g0.tab=0

Related commit https://github.com/trilogy-group/tu2k22-zhiyuangao/commit/a6e79b1bcd6c5e2a8e7f10b110b8f4dcd50ff684
![image](https://user-images.githubusercontent.com/110180090/184346085-01585060-f4e5-434f-9c61-ea31b24a055f.png)


![image](https://user-images.githubusercontent.com/110180090/184346628-ceaea553-c510-45c9-bb2f-b1b047befc1e.png)

**Comment by gao-ti** [comment]
## Milestone 2

![image](https://user-images.githubusercontent.com/110180090/184349602-caa3ef39-52fe-4a95-aa3f-d6642887beb6.png)

**Comment by kushal-ti** [comment]
the first milestone required you to inject trace context to your logs, should be pretty easy to accomplish with otel, do that, post screenshots and you can close this issue

Partial marks have been recorded, go for the full thing 😉

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184486559-ef4ca6f7-cd89-4d2d-9810-90a9c0b5d0a0.png)


@kushal-ti otel is tricky for me because my wsl doesn't have systemd.
Is this okay if I use the console exporter

**Comment by kushal-ti** [comment]
what's being printed here is actually the trace itself, not the logs. refer to https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/logging/logging.html to understand what i mean. You will have to add logging statements to you code and then call the relevant opentelemetry instrumentation to inject trace context into your logging statements

**Comment by gao-ti** [comment]
![image](https://user-images.githubusercontent.com/110180090/184532602-fa639172-f6a3-4455-a9bb-f60cc09900b3.png)

```
from opentelemetry.instrumentation.logging import LoggingInstrumentor
LoggingInstrumentor().instrument(set_logging_format=True)
LoggingInstrumentor(logging_format='%(msg)s [span_id=%(span_id)s]')
@api_view(['GET'])
def logtest():
    logger = logging.getLogger(__name__)
    logger.info('----test----')
```

**Comment by kushal-ti** [comment]
this works, score has been recorded, you may close the issue
